# Generated by Django 3.2.4 on 2021-08-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('visitorname', models.CharField(max_length=50)),
                ('tomeet', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('purpose', models.TextField()),
                ('mobile', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'Visitor',
            },
        ),
    ]
