# Generated by Django 3.2.4 on 2021-08-11 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210811_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organsier', models.CharField(max_length=50)),
                ('attendees', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('purpose', models.TextField()),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
